config/routes.rb
Rails.application.routes.draw do
  # devise_for :admin_users, ActiveAdmin::Devise.config
  # ActiveAdmin.routes(self)

  get '/terms', to: 'static_pages#terms'
  get '/privacy', to: 'static_pages#privacy'

  devise_for :users, controllers: {
    omniauth_callbacks: 'omniauth_callbacks'
  }

  resources :users, only: [:show, :edit, :update]

  root 'regions#index'

  resources :regions, only: [:index], shallow: true do
    resources :prefectures, only: [:show]
  end

  resources :place_search, only: [:index] do
    collection do
      get :search
    end
  end

  resources :off_road_circuits, only: [:show, :new, :create, :edit, :update, :destroy]

  resource :inquiry, only: [:new, :create], path_names: { new: '' } do
    collection do
      post :confirm
    end
  end

  namespace :api, { format: 'json' } do
    resources :users, only: [:index] do
      resources :favorite_courses, only: [:index, :create, :destroy]
      resources :practice_recodes, only: [:index, :show, :create, :edit, :update, :destroy]
    end

    resources :regions, only: [:index]

    resources :off_road_circuits, only: [:index]

    resources :plans, only: [:index, :create, :destroy]
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end
end

app/models/off_road_circuit.rb
class OffRoadCircuit < ApplicationRecord
  belongs_to :prefecture
  belongs_to :region
  has_many :photo, dependent: :destroy
  has_many :plan, dependent: :destroy
  
  has_many :favorite_courses, dependent: :delete_all
  has_many :users, through: :favorite_courses

  validates :name, presence: true
  validates :place_id, presence: true
  validates :prefecture_id, presence: true
  validates :region_id, presence: true
end

app/controllers/api/off_road_circuits_controller.rb
class Api::OffRoadCircuitsController < ActionController::API
  def index
    off_road_circuits = OffRoadCircuit.includes(:photo).where(prefecture_id: params[:prefecture_id])

    render json: {
      off_road_circuits: off_road_circuits.map do |circuit|
        {
          id: circuit.id,
          name: circuit.name,
          photo_url: circuit.photo[0]&.url
        }
      end
    }
  end
end

app/controllers/off_road_circuits_controller.rb
class OffRoadCircuitsController < ApplicationController
  before_action :admin_user, except: [:show]

  def show
    @off_road_circuit = OffRoadCircuit.find(params[:id])
    @detail = circuit_details(@off_road_circuit.place_id.to_sym)
  end

  def new
    @place_search = PlaceSearch.new(query: params[:place_id]).details

    prefecture_name = @place_search['result']['address_components'].each do |address|
      break address['long_name'] if address['types'][0] == 'administrative_area_level_1'
    end
    prefecture = Prefecture.find_by(name: prefecture_name)

    @off_road_circuit = OffRoadCircuit.new(
      name: @place_search['result']['name'],
      address: @place_search['result']['vicinity'],
      place_id: params[:place_id],
      prefecture_id: prefecture.id,
      region_id: prefecture.region_id
    )
  end

  def create
    @off_road_circuit = OffRoadCircuit.new(off_road_circuit_params)
    if @off_road_circuit.save
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
    @off_road_circuit = OffRoadCircuit.find(params[:id])
  end

  def update
    @off_road_circuit = OffRoadCircuit.find(params[:id])

    if @off_road_circuit.update(off_road_circuit_params)
      redirect_to @off_road_circuit
    else
      render 'edit'
    end
  end

  def destroy
    OffRoadCircuit.find(params[:id]).destroy
  end

  private

  def off_road_circuit_params
    params.require(:off_road_circuit).permit(
      :name,
      :address,
      :url,
      :place_id,
      :prefecture_id,
      :region_id
    )
  end

  def circuit_details(place_id)
    details = Rails.cache.fetch(place_id, expired_in: 10.days) do
      PlaceSearch.new(query: place_id).details
    end
    {
      rating: details.dig('result', 'rating'),
      vicinity: details.dig('result', 'vicinity')
     }
  end
end

app/views/off_road_circuits/destroy.html.slim
h1 OffRoadCircuits#destroy
p Find me in app/views/off_road_circuits/destroy.html.slim

app/views/off_road_circuits/edit.html.slim
h1 OffRoadCircuits#edit
p Find me in app/views/off_road_circuits/edit.html.slim

= @off_road_circuit.name

= form_with model: @off_road_circuit, local: true do |f|

  - if @off_road_circuit.errors.any?
    div id="error_explanation"
      div class="alert alert-danger"
        | The form contains #{pluralize(@off_road_circuit.errors.count, "error")}.

      ul
      - @off_road_circuit.errors.full_messages.each do |msg|
        li = msg

  = f.label :name
  = f.text_field :name

  = f.label :address
  = f.text_field :address

  = f.label :place_id
  = f.text_field :place_id

  = f.label :prefecture_id
  = f.collection_select :prefecture_id, Prefecture.all, :id, :name

  = f.label :region_id
  = f.collection_select :region_id, Region.all, :id, :name


  = f.submit "更 新"

app/views/off_road_circuits/new.html.slim
h1 OffRoadCircuits#new
p Find me in app/views/off_road_circuits/new.html.slim

= form_with model: @off_road_circuit, local: true do |f|

  - if @off_road_circuit.errors.any?
    div id="error_explanation"
      div class="alert alert-danger"
        | The form contains #{pluralize(@off_road_circuit.errors.count, "error")}.

      ul
      - @off_road_circuit.errors.full_messages.each do |msg|
        li = msg

  div class="input-field"
    = f.label :name
    = f.text_field :name

    = f.label :address
    = f.text_field :address

    = f.label :place_id
    = f.text_field :place_id

    = f.label :prefecture_id
    = f.collection_select :prefecture_id, Prefecture.all, :id, :name

    = f.label :region_id
    = f.collection_select :region_id, Region.all, :id, :name


    = f.submit "登 録"

app/views/off_road_circuits/show.html.slim
- set_meta_tags title: @off_road_circuit.name
- set_meta_tags description: "#{@off_road_circuit.name}のモトクロスコース情報。#{default_meta_tags[:description]}"
- set_meta_tags keywords: "#{@off_road_circuit.name},#{default_meta_tags[:keywords]}"

div.swiper-container
  div.swiper-wrapper
    - @off_road_circuit.photo.each do |photo|
      div.swiper-slide
        = image_tag photo.url
  div.swiper-pagination

  div.swiper-button-prev
  div.swiper-button-next

section.hero.is-info.is-bold
  div.hero-head

  div.hero-body
    div.container.has-text-centered
      h1.title
        = @off_road_circuit.name
      h2.subtitle
        = @detail[:rating]

        - if @detail[:rating]
          - @detail[:rating].to_i.times do |i|
            span.icon.mdi-18px.has-text-success
              i.fas.fa-star

          - decimal_part = @detail[:rating].to_s[/(\d+)\.+(\d+)/, 2].to_i
          = half_or_full_star(decimal_part)

      h3.subtitle
        = @off_road_circuit.address || @detail[:vicinity]

  nav.tabs.is-boxed.is-centered.main-menu.is-fullwidth#nav
    div.container
      ul
        li.is-active#1 data-target="pane-1"
          a
            span
             | 概要
        li#2 data-target="pane-2"
          a
            span
             | みんなの予定
        li#3 data-target="pane-3"
          a
            span
             | 口コミ
        li#4 data-target="pane-4"
          a
            span
             | 関連動画

  div.tab-content
    div.tab-pane#pane-1 style="display: block;"
      p
        strong
          | 準備中
    div.tab-pane#pane-2 style="display: none;"
      div class="container"
        div#calendar
          plan :circuit-id="#{@off_road_circuit.id}" :user-id="#{user_signed_in? ? current_user.id : 'null'}"
    div.tab-pane#pane-3 style="display: none;"
      p
        strong
          | 準備中：口コミ(Google)
    div.tab-pane#pane-4 style="display: none;"
      p
        strong
          | 準備中：関連動画


- if current_user.try(:admin?)
  p
  = link_to "#{@off_road_circuit.name}を編集", edit_off_road_circuit_path(@off_road_circuit)
  p
  = link_to "#{@off_road_circuit.name}を削除", @off_road_circuit, method: :delete, data: { confirm: '削除してよろしいですか？' }
p
= link_to '一覧に戻る', prefecture_path(@off_road_circuit.prefecture_id), data: { turbolinks: false }

= javascript_pack_tag 'off_road_circuits/form'

- content_for :footer
  div.content.has-text-right
    = image_tag 'powered_by_google_on_white.png', size: '85x85'