config/routes.rb
Rails.application.routes.draw do
  # devise_for :admin_users, ActiveAdmin::Devise.config
  # ActiveAdmin.routes(self)

  get '/terms', to: 'static_pages#terms'
  get '/privacy', to: 'static_pages#privacy'

  devise_for :users, controllers: {
    omniauth_callbacks: 'omniauth_callbacks'
  }

  resources :users, only: [:show, :edit, :update]

  root 'regions#index'

  resources :regions, only: [:index], shallow: true do
    resources :prefectures, only: [:show]
  end

  resources :place_search, only: [:index] do
    collection do
      get :search
    end
  end

  resources :off_road_circuits, only: [:show, :new, :create, :edit, :update, :destroy]

  resource :inquiry, only: [:new, :create], path_names: { new: '' } do
    collection do
      post :confirm
    end
  end

  namespace :api, { format: 'json' } do
    resources :users, only: [:index] do
      resources :favorite_courses, only: [:index, :create, :destroy]
      resources :practice_recodes, only: [:index, :show, :create, :edit, :update, :destroy]
    end

    resources :regions, only: [:index]

    resources :off_road_circuits, only: [:index]

    resources :plans, only: [:index, :create, :destroy]
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end
end

app/models/inquiry.rb
class Inquiry
  include ActiveModel::Model
  attr_accessor :title, :email, :message
  
  validates :title, presence: true, length: { maximum: 255 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, if: -> { email.present? }
  validates :message, presence: true,  length: { maximum: 2000 }
end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController
  def new
    @inquiry = Inquiry.new
  end

  def confirm
    @inquiry = Inquiry.new(inquiry_params)
    render :new unless @inquiry.valid?
  end

  def create
    @inquiry = Inquiry.new(inquiry_params)
    if @inquiry.valid?
      InquiryMailer.received_email(@inquiry).deliver
    else
      raise StandardError
    end
  end

  private

  def inquiry_params
    params.require(:inquiry).permit(:email, :title, :message)
  end
end

app/views/inquiries/confirm.html.slim
- set_meta_tags noindex: true, follow: false, nofollow: true

.hero-body.has-background-light
  .container.has-text-centered
    .column.is-6.is-offset-3
      h1.title お問い合わせ内容確認
    
      = form_for @inquiry, url: inquiry_path do |f|
        .field.has-text-left

          - if @inquiry.errors.any?
            .notification
              strong 入力内容にエラーがあります
              ul.help.is-danger
                - @inquiry.errors.full_messages.each do |msg|
                  li = msg

          label.label
            = f.label :email
            .control
              p = @inquiry.email

          label.label
            = f.label :title
            .control
              p = @inquiry.title
            
          label.label
            = f.label :message
            .control
              p = @inquiry.message
        
        - @inquiry.instance_values.each do |k, _v|
          - next if k == 'errors' || k == 'validation_context'
          = f.hidden_field k 

        .field
          .control
            = f.submit '送信', class: 'button is-block is-info is-fullwidth'

app/views/inquiries/create.html.slim
- set_meta_tags noindex: true, follow: false, nofollow: true

.hero-body.has-background-light
  .container.has-text-centered
    .column.is-6.is-offset-3
      h1.title.is-6.has-text-grey お問い合わせありがとうございました。
      p.title.is-6.has-text-grey 問い合わせ内容は管理者宛に送信しました。

app/views/inquiries/new.html.slim
- set_meta_tags noindex: true, follow: false, nofollow: true

.hero-body.has-background-light
  .container.has-text-centered
    .column.is-6.is-offset-3
      h1.title お問い合わせ
    
      = form_for @inquiry, url: confirm_inquiry_path do |f|
        .field.has-text-left

          - if @inquiry.errors.any?
            .notification
              strong 入力内容にエラーがあります
              ul.help.is-danger
                - @inquiry.errors.full_messages.each do |msg|
                  li = msg

          label.label
            = f.label :email
            .control
              = f.text_field :email, class: 'input', placeholder: 'e.g. example@gmail.com', type: 'email', pattern: "[\w+_-.]+@[a-z\d_-]+\.[a-z\d._-]+"

          label.label
            = f.label :title
            .control
              = f.text_field :title, class: 'input', type: 'text', required: true
            
          label.label
            = f.label :message
            .control
              = f.text_area :message, class: 'textarea', required: true

        .field
          .control
            = f.submit '確認', class: 'button is-block is-info is-fullwidth'