config/routes.rb
Rails.application.routes.draw do
  # devise_for :admin_users, ActiveAdmin::Devise.config
  # ActiveAdmin.routes(self)

  get '/terms', to: 'static_pages#terms'
  get '/privacy', to: 'static_pages#privacy'

  devise_for :users, controllers: {
    omniauth_callbacks: 'omniauth_callbacks'
  }

  resources :users, only: [:show, :edit, :update]

  root 'regions#index'

  resources :regions, only: [:index], shallow: true do
    resources :prefectures, only: [:show]
  end

  resources :place_search, only: [:index] do
    collection do
      get :search
    end
  end

  resources :off_road_circuits, only: [:show, :new, :create, :edit, :update, :destroy]

  resource :inquiry, only: [:new, :create], path_names: { new: '' } do
    collection do
      post :confirm
    end
  end

  namespace :api, { format: 'json' } do
    resources :users, only: [:index] do
      resources :favorite_courses, only: [:index, :create, :destroy]
      resources :practice_recodes, only: [:index, :show, :create, :edit, :update, :destroy]
    end

    resources :regions, only: [:index]

    resources :off_road_circuits, only: [:index]

    resources :plans, only: [:index, :create, :destroy]
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end
end

app/models/place_search.rb
class PlaceSearch
  include ActiveModel::Model

  attr_accessor :query

  validates :query, presence: true

  def search
    google_api.text_search(@query)
  end

  def details
    google_api.details(@query)
  end

  def photo
    google_api.photo(@query)
  end

  private

  def google_api
    GoogleApi::Client.new
  end
end

app/controllers/place_search_controller.rb
class PlaceSearchController < ApplicationController
  before_action :admin_user

  def search
  end

  def index
    @place_search = PlaceSearch.new(query: params[:q]).search
  end
end

app/views/place_search/create.html.slim
h1 PlaceSearch#create
p Find me in app/views/place_search/create.html.slim

- @place_search.each do |name, place_id|
  li
    = link_to "#{name}を登録する", new_off_road_circuit_path(place_id: place_id)

app/views/place_search/index.html.slim
h1 PlaceSearch#index
p Find me in app/views/place_search/index.html.slim

- @place_search.each do |name, place_id|
  li
    = link_to "#{name}を登録する", new_off_road_circuit_path(place_id: place_id)

app/views/place_search/search.html.slim
h1 PlaceSearch#search
p Find me in app/views/place_search/search.html.slim

= form_with(url: place_search_index_path, method: :get, local: true) do |f|

  = f.text_field :q
  = f.submit '検索', name: nil