config/routes.rb
Rails.application.routes.draw do
  # devise_for :admin_users, ActiveAdmin::Devise.config
  # ActiveAdmin.routes(self)

  get '/terms', to: 'static_pages#terms'
  get '/privacy', to: 'static_pages#privacy'

  devise_for :users, controllers: {
    omniauth_callbacks: 'omniauth_callbacks'
  }

  resources :users, only: [:show, :edit, :update]

  root 'regions#index'

  resources :regions, only: [:index], shallow: true do
    resources :prefectures, only: [:show]
  end

  resources :place_search, only: [:index] do
    collection do
      get :search
    end
  end

  resources :off_road_circuits, only: [:show, :new, :create, :edit, :update, :destroy]

  resource :inquiry, only: [:new, :create], path_names: { new: '' } do
    collection do
      post :confirm
    end
  end

  namespace :api, { format: 'json' } do
    resources :users, only: [:index] do
      resources :favorite_courses, only: [:index, :create, :destroy]
      resources :practice_recodes, only: [:index, :show, :create, :edit, :update, :destroy]
    end

    resources :regions, only: [:index]

    resources :off_road_circuits, only: [:index]

    resources :plans, only: [:index, :create, :destroy]
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end
end

app/views/layouts/application.html.slim
doctype html
html
  head
    = display_meta_tags(default_meta_tags)
    = csrf_meta_tags
    = csp_meta_tag

    meta name="viewport" content="width=device-width, initial-scale=1"

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = analytics_init if Rails.env.production?

  body
    nav.navbar.is-white role="navigation" aria-label="main navigation"
      div.container
        div.navbar-brand
          = link_to root_path, class: 'navbar-item brand-text', data: { turbolinks: false } do
            = image_tag 'dirt_awesome_logo.png', size: '240x50'
          div.navbar-burger.burger data-target="navMenu"
            span aria-hidden="true"
            span aria-hidden="true"
            span aria-hidden="true"

        div.navbar-menu id="navMenu"
          div.navbar-start
            - if user_signed_in?
              span.navbar-item
                = link_to user_path(current_user), class: 'button is-outlined is-primary', data: { turbolinks: false }
                  span.icon
                    i.fas.fa-user
                  span マイページ
              = link_to 'プロフィール変更', edit_user_path(current_user), class: 'navbar-item'
              = link_to 'パスワード変更', edit_user_registration_path, class: 'navbar-item'
              = link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'navbar-item'
            - else
              span.navbar-item
                = link_to "ユーザー登録", new_user_registration_path, class: 'button is-outlined'
              pan.navbar-item
                = link_to 'ログイン', new_user_session_path, class: 'button is-white'
    
    - if notice
      .notification.is-primary = notice
    - if alert
      .notification.is-danger = alert

    = yield

    footer.footer
      .container
        = yield :footer
        nav.level
          p.level-item
            | © 2018 dirt awesome
          p.level-item
            = link_to '利用規約', terms_path, class: 'link is-info'
          p.level-item
            = link_to 'プライバシーポリシー', privacy_path, class: 'link is-info'
          p.level-item
            = link_to 'お問い合わせ', new_inquiry_path, class: 'link is-info'